apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      containers:
        - name: postgres
          image: postgres:18

          ports:
            - containerPort: 5432

          env:
            - name: POSTGRES_DB
              value: "taskdb"

            - name: POSTGRES_USER
              value: "api_tester"

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          volumeMounts:
            # Script SQL exécuté lors de l'initialisation
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d

            # Données PostgreSQL persistantes
            - name: postgres-data
              mountPath: /var/lib/postgresql

      volumes:
        # init.sql provenant du ConfigMap postgres-init
        - name: init-script
          configMap:
            name: postgres-init

        # Stockage persistant PostgreSQL
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
